apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-react
  namespace: food-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-react
  template:
    metadata:
      labels:
        app: food-react
    spec:
      containers:
      - name: food-react
        image: ghcr.io/vikasrajput0112/food-react-website:12
        ports:
        - containerPort: 80
