apiVersion: v1
kind: Service
metadata:
  name: food-react-service
  namespace: food-app
spec:
  type: NodePort
  selector:
    app: food-react
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31380
