apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: food-react
spec:
  project: default
  source:
    repoURL: https://github.com/<github-username>/food-react-gitops.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: food-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
